##############################################################################
# Source formatting

[tool.black]
line-length = 79
target-version = ["py35"]

##############################################################################
# Style checking

[tool.ruff]
ignore = [
    "N811",
    "N812",
    "N813",
    "N814",
]
line-length = 79
select = [
    "C9",
    "E",
    "F",
    "N",
    "Q",
    "W",
]

[tool.ruff.flake8-quotes]
inline-quotes = "double"

[tool.ruff.mccabe]
max-complexity = 15

##############################################################################
# Type checking

[tool.mypy]
warn_unused_configs = true
ignore_missing_imports = true

disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true

##############################################################################
# Coverage support

[tool.coverage.run]
branch = true
